version: '3'
services:
  web:
    build: ./web
    entrypoint:
      - APACHE_RUN_USER=www-data
    volumes:
      - ${APP_PATH_HOST} = ${APP_PATH_CONTAINER}
    ports:
      - 8080:80
    working_dir: ${APP_PATH_CONTAINER}